 ###LocalHost 
###GET ALL cars
GET http://localhost:3000/cars 

###GET cars BY ID
GET http://localhost:3000/cars/67e5a8136b0c94e6754b4433

###CREATE cars
POST http://localhost:3000/cars HTTP/1.1
Content-type: application/json

{
    "model": "phantom" ,
    "make": "rolls royce",
    "miles": "9900",
    "color": "pink",
    "year": "1998",
    "engine": "v23",
    "price": "1000000000",
    "registration": "fnv 456",
  }



###PUT Cars
PUT http://localhost:3000/cars/ HTTP/1.1
content-type: application/json

 {

    
    "model": "camry" ,
    "make": "toyota",
    "miles": "6700",
    "color": "black",
    "year": "2019",
    "engine": "v6",
    "price": "20000",
    "registration": "kbc 123",
  }

###delete car
delete http://localhost:3000/cars/ HTTP/1.1
content-type: application/json




